import Head from "next/head";
import { NextPage } from "next";
import Header from "@/components/Header";
import Login from "@/components/Login";

import { useContract, useMetamask, useAddress } from "@thirdweb-dev/react";

const Home: NextPage = () => {
    const address = useAddress();

    if (!address) return <Login />;

    return (
        <div className="bg-[#091B18] min-h-screen flex flex-col">
            <Head>
                <title>Lucky Draw</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
        </div>
    );
};

export default Home;
